name: merkle_tree
description: merkle tree in dart.
version: 1.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  sm_crypto: ^1.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
